// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview A Genkit flow that improves the quality of generated code by suggesting optimizations and ensuring maintainability.
 *
 * - improveCodeQuality - A function that takes generated code as input and returns improved code with suggestions.
 * - ImproveCodeQualityInput - The input type for the improveCodeQuality function.
 * - ImproveCodeQualityOutput - The return type for the improveCodeQuality function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ImproveCodeQualityInputSchema = z.object({
  code: z.string().describe('The code to be improved.'),
});
export type ImproveCodeQualityInput = z.infer<typeof ImproveCodeQualityInputSchema>;

const ImproveCodeQualityOutputSchema = z.object({
  improvedCode: z.string().describe('The improved code with suggested optimizations.'),
  suggestions: z.string().describe('The suggestions for improving the code quality.'),
});
export type ImproveCodeQualityOutput = z.infer<typeof ImproveCodeQualityOutputSchema>;

export async function improveCodeQuality(input: ImproveCodeQualityInput): Promise<ImproveCodeQualityOutput> {
  return improveCodeQualityFlow(input);
}

const prompt = ai.definePrompt({
  name: 'improveCodeQualityPrompt',
  input: {schema: ImproveCodeQualityInputSchema},
  output: {schema: ImproveCodeQualityOutputSchema},
  prompt: `You are an AI code quality expert. Analyze the given code and provide an improved version along with suggestions for better component structure, responsiveness, code quality, and maintainability.

Code to analyze:
{{{code}}}

Output the improved code and a list of suggestions in the following format:

Improved Code:
```
(Improved Code Here)
```

Suggestions:
- (Suggestion 1)
- (Suggestion 2)
- (Suggestion 3)
...
`,
});

const improveCodeQualityFlow = ai.defineFlow(
  {
    name: 'improveCodeQualityFlow',
    inputSchema: ImproveCodeQualityInputSchema,
    outputSchema: ImproveCodeQualityOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
